#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/resource.h>
#include <errno.h>

#include <bpf/libbpf.h>
#include <bpf/bpf.h>

#include "sigsnoop.skel.h" // Generated by bpftool or libbpf
#include "teste_tc.skel.h" // Generated by bpftool or libbpf
                                 
/***********************************************************/                           
int main(int argc, char **argv){
    struct sigsnoop_bpf *skel;

    skel = sigsnoop_bpf__open_and_load();
    if ( !skel ){
        perror("Erro ao abrir e carregar o skeleto do programa");
        sigsnoop_bpf__destroy(skel);
        exit(1);
    }

    int ret_attach = sigsnoop_bpf__attach(skel);
    if (ret_attach){
        perror("Erro ao aclopar programa");
        sigsnoop_bpf__destroy(skel);
        exit(1);
    }

    printf("\nCtrl+C para parar\nxxx Programa carregado e aclopado xxx \n");

    while(1){
        ;
    }

    return 0;
}
